CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'resident'
    CHECK (role IN ('admin', 'resident')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS flats (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  flat_no VARCHAR(50) NOT NULL UNIQUE,
  floor_no INTEGER NOT NULL,
  owner_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  maintenance_charge NUMERIC(10, 2) NOT NULL DEFAULT 0.00
    CHECK (maintenance_charge >= 0)
);

CREATE TABLE IF NOT EXISTS maintenance (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  flat_id INTEGER REFERENCES flats(id) ON DELETE SET NULL,
  month INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
  year INTEGER NOT NULL CHECK (year >= 2000),
  amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00 CHECK (amount >= 0),
  status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('paid', 'pending')),
  title VARCHAR(255),
  due_date DATE,
  description TEXT,
  maintenance_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
    CHECK (maintenance_status IN ('ACTIVE', 'CLOSED')),
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (month, year)
);

CREATE TABLE IF NOT EXISTS maintenance_bills (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  maintenance_id INTEGER NOT NULL REFERENCES maintenance(id) ON DELETE CASCADE,
  resident_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  flat_id INTEGER NOT NULL REFERENCES flats(id) ON DELETE CASCADE,
  amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00 CHECK (amount >= 0),
  late_fee NUMERIC(10, 2) NOT NULL DEFAULT 0.00 CHECK (late_fee >= 0),
  total_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00 CHECK (total_amount >= 0),
  payment_status VARCHAR(20) NOT NULL DEFAULT 'Pending'
    CHECK (payment_status IN ('Pending', 'Under Review', 'Paid', 'Rejected')),
  payment_date TIMESTAMPTZ,
  due_date DATE,
  remarks TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (maintenance_id, resident_id, flat_id)
);

CREATE TABLE IF NOT EXISTS payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_id INTEGER NOT NULL REFERENCES maintenance_bills(id) ON DELETE CASCADE,
  payment_method VARCHAR(50) NOT NULL,
  transaction_id VARCHAR(255),
  amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00 CHECK (amount > 0),
  payment_status VARCHAR(20) NOT NULL DEFAULT 'Pending'
    CHECK (payment_status IN ('Pending', 'Under Review', 'Paid', 'Rejected')),
  paid_at TIMESTAMPTZ,
  screenshot_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (bill_id, transaction_id)
);

CREATE TABLE IF NOT EXISTS complaints (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'in_progress', 'resolved')),
  reply TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS notices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS staff (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  role VARCHAR(100) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  salary NUMERIC(10, 2) NOT NULL CHECK (salary >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS visitors (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resident_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  visit_time TIMESTAMPTZ NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS parcels (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resident_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  courier_name VARCHAR(255),
  tracking_id VARCHAR(255),
  status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'delivered')),
  received_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS activities (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resident_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_flats_owner_id ON flats(owner_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_bills_resident_id ON maintenance_bills(resident_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_bills_status ON maintenance_bills(payment_status);
CREATE INDEX IF NOT EXISTS idx_payments_bill_id ON payments(bill_id);
CREATE INDEX IF NOT EXISTS idx_complaints_user_id ON complaints(user_id);
CREATE INDEX IF NOT EXISTS idx_visitors_resident_id ON visitors(resident_id);
CREATE INDEX IF NOT EXISTS idx_parcels_resident_id ON parcels(resident_id);
CREATE INDEX IF NOT EXISTS idx_activities_resident_id ON activities(resident_id);

DROP TRIGGER IF EXISTS maintenance_set_updated_at ON maintenance;
CREATE TRIGGER maintenance_set_updated_at
BEFORE UPDATE ON maintenance
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS maintenance_bills_set_updated_at ON maintenance_bills;
CREATE TRIGGER maintenance_bills_set_updated_at
BEFORE UPDATE ON maintenance_bills
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS payments_set_updated_at ON payments;
CREATE TRIGGER payments_set_updated_at
BEFORE UPDATE ON payments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE flats ENABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance ENABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance_bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE complaints ENABLE ROW LEVEL SECURITY;
ALTER TABLE notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE visitors ENABLE ROW LEVEL SECURITY;
ALTER TABLE parcels ENABLE ROW LEVEL SECURITY;
ALTER TABLE activities ENABLE ROW LEVEL SECURITY;

