ALTER TABLE maintenance_bills
  ADD COLUMN IF NOT EXISTS bill_number VARCHAR(40),
  ADD COLUMN IF NOT EXISTS invoice_number VARCHAR(40),
  ADD COLUMN IF NOT EXISTS paid_amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS remaining_amount NUMERIC(10, 2) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS maintenance_categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
  calculation_type VARCHAR(20) NOT NULL DEFAULT 'FIXED'
    CHECK (calculation_type IN ('FIXED', 'PER_SQ_FT')),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS maintenance_bill_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_id INTEGER NOT NULL REFERENCES maintenance_bills(id) ON DELETE CASCADE,
  category_id INTEGER REFERENCES maintenance_categories(id) ON DELETE SET NULL,
  name VARCHAR(120) NOT NULL,
  amount NUMERIC(10, 2) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS maintenance_expenses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expense_number VARCHAR(40) NOT NULL UNIQUE,
  category VARCHAR(100) NOT NULL,
  vendor VARCHAR(180) NOT NULL,
  amount NUMERIC(12, 2) NOT NULL,
  expense_date DATE NOT NULL,
  invoice_url TEXT,
  description TEXT,
  payment_method VARCHAR(50),
  status VARCHAR(20) NOT NULL DEFAULT 'Paid'
    CHECK (status IN ('Pending', 'Paid', 'Cancelled')),
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS late_fee_rules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  grace_period INTEGER NOT NULL DEFAULT 0,
  penalty_type VARCHAR(20) NOT NULL DEFAULT 'DAILY'
    CHECK (penalty_type IN ('DAILY', 'WEEKLY', 'MONTHLY')),
  penalty_amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
  maximum_late_fee NUMERIC(10, 2) NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS maintenance_disputes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_id INTEGER NOT NULL REFERENCES maintenance_bills(id) ON DELETE CASCADE,
  resident_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  subject VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'Open'
    CHECK (status IN ('Open', 'In Review', 'Resolved', 'Rejected')),
  admin_response TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS maintenance_audit_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  action VARCHAR(60) NOT NULL,
  entity_type VARCHAR(60) NOT NULL,
  entity_id INTEGER,
  details JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS app_settings (
  setting_key VARCHAR(100) PRIMARY KEY,
  setting_value JSONB NOT NULL,
  updated_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS admin_notification_reads (
  user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  last_read_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash VARCHAR(255) NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_password_reset_token_hash ON password_reset_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_maintenance_bill_items_bill_id ON maintenance_bill_items(bill_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_expenses_date ON maintenance_expenses(expense_date);
CREATE INDEX IF NOT EXISTS idx_maintenance_disputes_bill_id ON maintenance_disputes(bill_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_audit_logs_user_id ON maintenance_audit_logs(user_id);

DROP TRIGGER IF EXISTS maintenance_categories_set_updated_at ON maintenance_categories;
CREATE TRIGGER maintenance_categories_set_updated_at
BEFORE UPDATE ON maintenance_categories
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS maintenance_disputes_set_updated_at ON maintenance_disputes;
CREATE TRIGGER maintenance_disputes_set_updated_at
BEFORE UPDATE ON maintenance_disputes
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS app_settings_set_updated_at ON app_settings;
CREATE TRIGGER app_settings_set_updated_at
BEFORE UPDATE ON app_settings
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

INSERT INTO maintenance_categories (name, amount) VALUES
  ('Water Charges', 500),
  ('Security Charges', 800),
  ('Lift Maintenance', 350),
  ('Housekeeping', 600),
  ('Sinking Fund', 750),
  ('Common Area Maintenance', 500)
ON CONFLICT (name) DO NOTHING;

ALTER TABLE maintenance_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance_bill_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance_expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE late_fee_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance_disputes ENABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance_audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_notification_reads ENABLE ROW LEVEL SECURITY;
ALTER TABLE password_reset_tokens ENABLE ROW LEVEL SECURITY;
