-- Drop referencing tables first
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS maintenance_disputes CASCADE;
DROP TABLE IF EXISTS maintenance_bill_items CASCADE;
DROP TABLE IF EXISTS maintenance_bills CASCADE;
DROP TABLE IF EXISTS maintenance CASCADE;

-- Recreate maintenance table with all requested fields
CREATE TABLE maintenance (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resident_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  flat_id INTEGER REFERENCES flats(id) ON DELETE SET NULL,
  title VARCHAR(255) NOT NULL,
  month INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
  year INTEGER NOT NULL CHECK (year >= 2000),
  amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00 CHECK (amount >= 0),
  paid_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00 CHECK (paid_amount >= 0),
  remaining_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00 CHECK (remaining_amount >= 0),
  status VARCHAR(20) NOT NULL DEFAULT 'Pending'
    CHECK (status IN ('Paid', 'Pending', 'Overdue', 'Under Review', 'Rejected')),
  payment_date TIMESTAMPTZ,
  due_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Recreate payments table referencing maintenance(id) via bill_id
CREATE TABLE payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_id INTEGER NOT NULL REFERENCES maintenance(id) ON DELETE CASCADE,
  payment_method VARCHAR(50) NOT NULL,
  transaction_id VARCHAR(255),
  amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00 CHECK (amount > 0),
  payment_status VARCHAR(20) NOT NULL DEFAULT 'Pending'
    CHECK (payment_status IN ('Pending', 'Under Review', 'Paid', 'Rejected')),
  paid_at TIMESTAMPTZ,
  screenshot_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (bill_id, transaction_id)
);

-- Recreate maintenance_disputes referencing maintenance(id) via bill_id
CREATE TABLE maintenance_disputes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_id INTEGER NOT NULL REFERENCES maintenance(id) ON DELETE CASCADE,
  resident_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  subject VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'Open'
    CHECK (status IN ('Open', 'In Review', 'Resolved', 'Rejected')),
  admin_response TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Recreate maintenance_bill_items referencing maintenance(id) via bill_id
CREATE TABLE maintenance_bill_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_id INTEGER NOT NULL REFERENCES maintenance(id) ON DELETE CASCADE,
  category_id INTEGER REFERENCES maintenance_categories(id) ON DELETE SET NULL,
  name VARCHAR(120) NOT NULL,
  amount NUMERIC(10, 2) NOT NULL DEFAULT 0
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_maintenance_resident_id ON maintenance(resident_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_flat_id ON maintenance(flat_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_status ON maintenance(status);
CREATE INDEX IF NOT EXISTS idx_payments_bill_id ON payments(bill_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_disputes_bill_id ON maintenance_disputes(bill_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_bill_items_bill_id ON maintenance_bill_items(bill_id);

-- Enable Row Level Security (RLS)
ALTER TABLE maintenance ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance_disputes ENABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance_bill_items ENABLE ROW LEVEL SECURITY;
