ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_reference_id_fkey;

CREATE TABLE IF NOT EXISTS noc_types (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  description TEXT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO noc_types (name, description, active)
VALUES
  ('Flat Transfer', 'NOC for ownership transfer or resale process.', TRUE),
  ('Home Loan', 'NOC required for bank or financial institution home loan processing.', TRUE),
  ('Renovation Permission', 'NOC for interior or structural renovation permission.', TRUE),
  ('Tenant Registration', 'NOC for tenant registration and police verification.', TRUE),
  ('Vehicle Parking', 'NOC for vehicle parking allocation or verification.', TRUE),
  ('Commercial Use Permission', 'NOC for permission related to commercial use.', TRUE),
  ('Duplicate Share Certificate', 'NOC for issuing duplicate share certificate.', TRUE),
  ('Other', 'General purpose NOC request.', TRUE)
ON CONFLICT (name) DO NOTHING;

CREATE TABLE IF NOT EXISTS noc_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_number VARCHAR(40) NOT NULL UNIQUE,
  resident_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  flat_id INTEGER REFERENCES flats(id) ON DELETE SET NULL,
  noc_type VARCHAR(120) NOT NULL,
  purpose TEXT NOT NULL,
  remarks TEXT,
  documents TEXT,
  status VARCHAR(30) NOT NULL DEFAULT 'Pending'
    CHECK (status IN ('Pending', 'Under Review', 'Approved', 'Rejected')),
  requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  approved_at TIMESTAMPTZ,
  approved_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  rejected_reason TEXT,
  admin_remarks TEXT,
  pdf_url TEXT,
  verification_number VARCHAR(80),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS noc_audit_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  noc_request_id INTEGER NOT NULL REFERENCES noc_requests(id) ON DELETE CASCADE,
  action VARCHAR(80) NOT NULL,
  actor_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  remarks TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_noc_requests_resident_id ON noc_requests(resident_id);
CREATE INDEX IF NOT EXISTS idx_noc_requests_flat_id ON noc_requests(flat_id);
CREATE INDEX IF NOT EXISTS idx_noc_requests_status ON noc_requests(status);
CREATE INDEX IF NOT EXISTS idx_noc_audit_logs_request_id ON noc_audit_logs(noc_request_id);

ALTER TABLE noc_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE noc_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE noc_audit_logs ENABLE ROW LEVEL SECURITY;
