CREATE TABLE IF NOT EXISTS flat_types (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  default_maintenance_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00 CHECK (default_maintenance_amount >= 0),
  description TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE flat_types ENABLE ROW LEVEL SECURITY;

ALTER TABLE flats ADD COLUMN IF NOT EXISTS flat_type_id INTEGER REFERENCES flat_types(id) ON DELETE SET NULL;

ALTER TABLE maintenance ADD COLUMN IF NOT EXISTS flat_type_id INTEGER REFERENCES flat_types(id) ON DELETE SET NULL;
ALTER TABLE maintenance ADD COLUMN IF NOT EXISTS default_maintenance_amount NUMERIC(10, 2) DEFAULT 0.00 CHECK (default_maintenance_amount >= 0);
ALTER TABLE maintenance ADD COLUMN IF NOT EXISTS final_maintenance_amount NUMERIC(10, 2) DEFAULT 0.00 CHECK (final_maintenance_amount >= 0);
ALTER TABLE maintenance ADD COLUMN IF NOT EXISTS is_custom_amount BOOLEAN DEFAULT FALSE;
ALTER TABLE maintenance ADD COLUMN IF NOT EXISTS custom_reason TEXT;
ALTER TABLE maintenance ADD COLUMN IF NOT EXISTS edited_by INTEGER REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE maintenance ADD COLUMN IF NOT EXISTS edited_at TIMESTAMPTZ;

-- Backfill existing data safely
UPDATE maintenance 
SET default_maintenance_amount = amount, 
    final_maintenance_amount = amount 
WHERE default_maintenance_amount IS NULL OR default_maintenance_amount = 0.00;
