-- Alter users role constraint
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE users ADD CONSTRAINT users_role_check CHECK (role IN ('admin', 'resident', 'committee'));

-- Create meetings table
CREATE TABLE IF NOT EXISTS meetings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  meeting_type VARCHAR(50) NOT NULL CHECK (meeting_type IN ('Annual General Meeting (AGM)', 'Committee Meeting', 'Emergency Meeting', 'Budget Meeting', 'Maintenance Meeting', 'Special Meeting', 'Other')),
  meeting_date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  venue VARCHAR(255) NOT NULL,
  description TEXT,
  priority VARCHAR(20) NOT NULL DEFAULT 'Normal' CHECK (priority IN ('Low', 'Normal', 'High', 'Urgent')),
  notify_residents BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(20) NOT NULL DEFAULT 'Scheduled' CHECK (status IN ('Scheduled', 'Cancelled', 'Completed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT check_meeting_times CHECK (end_time > start_time)
);

-- Enable RLS for meetings
ALTER TABLE meetings ENABLE ROW LEVEL SECURITY;

-- Create meeting_agendas table
CREATE TABLE IF NOT EXISTS meeting_agendas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id INTEGER NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
  item_text TEXT NOT NULL,
  order_index INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS for meeting_agendas
ALTER TABLE meeting_agendas ENABLE ROW LEVEL SECURITY;

-- Create meeting_attendance table
CREATE TABLE IF NOT EXISTS meeting_attendance (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id INTEGER NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
  resident_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status VARCHAR(20) NOT NULL DEFAULT 'Absent' CHECK (status IN ('Present', 'Absent', 'Late', 'Excused')),
  marked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (meeting_id, resident_id)
);

-- Enable RLS for meeting_attendance
ALTER TABLE meeting_attendance ENABLE ROW LEVEL SECURITY;

-- Create meeting_reports table (Minutes of Meetings)
CREATE TABLE IF NOT EXISTS meeting_reports (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id INTEGER NOT NULL UNIQUE REFERENCES meetings(id) ON DELETE CASCADE,
  summary TEXT,
  discussion TEXT,
  decisions_taken TEXT,
  remarks TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS for meeting_reports
ALTER TABLE meeting_reports ENABLE ROW LEVEL SECURITY;

-- Create meeting_actions table
CREATE TABLE IF NOT EXISTS meeting_actions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id INTEGER NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
  action_text TEXT NOT NULL,
  assigned_to INTEGER REFERENCES users(id) ON DELETE SET NULL,
  due_date DATE,
  priority VARCHAR(20) NOT NULL DEFAULT 'Normal' CHECK (priority IN ('Low', 'Normal', 'High', 'Urgent')),
  status VARCHAR(20) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'In Progress', 'Completed', 'Cancelled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS for meeting_actions
ALTER TABLE meeting_actions ENABLE ROW LEVEL SECURITY;

-- Create meeting_votes table
CREATE TABLE IF NOT EXISTS meeting_votes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id INTEGER NOT NULL UNIQUE REFERENCES meetings(id) ON DELETE CASCADE,
  question VARCHAR(500) NOT NULL,
  yes_count INTEGER NOT NULL DEFAULT 0,
  no_count INTEGER NOT NULL DEFAULT 0,
  abstain_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS for meeting_votes
ALTER TABLE meeting_votes ENABLE ROW LEVEL SECURITY;

-- Create meeting_resident_votes table (to track single votes)
CREATE TABLE IF NOT EXISTS meeting_resident_votes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vote_id INTEGER NOT NULL REFERENCES meeting_votes(id) ON DELETE CASCADE,
  resident_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  choice VARCHAR(20) NOT NULL CHECK (choice IN ('YES', 'NO', 'ABSTAIN')),
  voted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (vote_id, resident_id)
);

-- Enable RLS for meeting_resident_votes
ALTER TABLE meeting_resident_votes ENABLE ROW LEVEL SECURITY;

-- Create meeting_documents table
CREATE TABLE IF NOT EXISTS meeting_documents (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id INTEGER REFERENCES meetings(id) ON DELETE CASCADE,
  report_id INTEGER REFERENCES meeting_reports(id) ON DELETE CASCADE,
  file_path TEXT NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_type VARCHAR(100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS for meeting_documents
ALTER TABLE meeting_documents ENABLE ROW LEVEL SECURITY;
