-- Alter users role check constraint to support super_admin
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE users ADD CONSTRAINT users_role_check CHECK (role IN ('admin', 'resident', 'committee', 'super_admin'));

-- Alter maintenance table (bills) to add write-off columns
ALTER TABLE maintenance ADD COLUMN IF NOT EXISTS write_off_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00 CHECK (write_off_amount >= 0);
ALTER TABLE maintenance ADD COLUMN IF NOT EXISTS maintenance_write_off_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00 CHECK (maintenance_write_off_amount >= 0);
ALTER TABLE maintenance ADD COLUMN IF NOT EXISTS penalty_write_off_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00 CHECK (penalty_write_off_amount >= 0);
ALTER TABLE maintenance ADD COLUMN IF NOT EXISTS write_off_status VARCHAR(50) DEFAULT NULL;

-- Create write_offs table
CREATE TABLE IF NOT EXISTS write_offs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_id INTEGER NOT NULL REFERENCES maintenance(id) ON DELETE CASCADE,
  type VARCHAR(50) NOT NULL CHECK (type IN ('Maintenance', 'Penalty', 'Full')),
  amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00 CHECK (amount >= 0),
  maintenance_write_off_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00 CHECK (maintenance_write_off_amount >= 0),
  penalty_write_off_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00 CHECK (penalty_write_off_amount >= 0),
  reason TEXT NOT NULL,
  admin_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  admin_name VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS for write_offs
ALTER TABLE write_offs ENABLE ROW LEVEL SECURITY;
