CREATE TABLE IF NOT EXISTS society_rules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  category VARCHAR(100) NOT NULL DEFAULT 'General',
  priority VARCHAR(20) NOT NULL DEFAULT 'normal'
    CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
  status VARCHAR(20) NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'published', 'archived')),
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  published_at TIMESTAMPTZ,
  archived_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS society_rule_acknowledgements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_id INTEGER NOT NULL REFERENCES society_rules(id) ON DELETE CASCADE,
  resident_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  read_at TIMESTAMPTZ,
  acknowledged_at TIMESTAMPTZ,
  acknowledgement_text TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (rule_id, resident_id)
);

CREATE INDEX IF NOT EXISTS idx_society_rules_status ON society_rules(status);
CREATE INDEX IF NOT EXISTS idx_society_rules_category ON society_rules(category);
CREATE INDEX IF NOT EXISTS idx_society_rules_priority ON society_rules(priority);
CREATE INDEX IF NOT EXISTS idx_society_rules_created_at ON society_rules(created_at);
CREATE INDEX IF NOT EXISTS idx_rule_ack_rule_id ON society_rule_acknowledgements(rule_id);
CREATE INDEX IF NOT EXISTS idx_rule_ack_resident_id ON society_rule_acknowledgements(resident_id);
CREATE INDEX IF NOT EXISTS idx_rule_ack_acknowledged_at ON society_rule_acknowledgements(acknowledged_at);

DO $$
DECLARE
  constraint_name TEXT;
BEGIN
  SELECT tc.constraint_name
  INTO constraint_name
  FROM information_schema.table_constraints tc
  JOIN information_schema.key_column_usage kcu
    ON tc.constraint_name = kcu.constraint_name
   AND tc.table_schema = kcu.table_schema
  WHERE tc.table_schema = 'public'
    AND tc.table_name = 'notifications'
    AND tc.constraint_type = 'FOREIGN KEY'
    AND kcu.column_name = 'reference_id'
  LIMIT 1;

  IF constraint_name IS NOT NULL THEN
    EXECUTE FORMAT('ALTER TABLE notifications DROP CONSTRAINT %I', constraint_name);
  END IF;
END;
$$;

DROP TRIGGER IF EXISTS society_rules_set_updated_at ON society_rules;
CREATE TRIGGER society_rules_set_updated_at
BEFORE UPDATE ON society_rules
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS society_rule_acknowledgements_set_updated_at ON society_rule_acknowledgements;
CREATE TRIGGER society_rule_acknowledgements_set_updated_at
BEFORE UPDATE ON society_rule_acknowledgements
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE society_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE society_rule_acknowledgements ENABLE ROW LEVEL SECURITY;
