-- 028_meeting_management_enhancements.sql
-- Enhancement migration for complete Meeting Management module

-- 1. Ensure Compulsory meeting, fine options, and meeting status in meetings table
ALTER TABLE meetings ADD COLUMN IF NOT EXISTS is_compulsory BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE meetings ADD COLUMN IF NOT EXISTS fine_amount NUMERIC(10, 2) DEFAULT 0.00;
ALTER TABLE meetings ADD COLUMN IF NOT EXISTS fine_due_days INTEGER DEFAULT 7;
ALTER TABLE meetings ADD COLUMN IF NOT EXISTS qr_code_token VARCHAR(255);

-- Update status check constraint on meetings to include 'Ongoing' if missing
ALTER TABLE meetings DROP CONSTRAINT IF EXISTS meetings_status_check;
ALTER TABLE meetings ADD CONSTRAINT meetings_status_check CHECK (status IN ('Scheduled', 'Upcoming', 'Ongoing', 'Completed', 'Cancelled'));

-- 2. Meeting Fines table
CREATE TABLE IF NOT EXISTS meeting_fines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id INTEGER NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
  resident_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  reason VARCHAR(255) DEFAULT 'Absent in Compulsory Meeting',
  due_date DATE NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Paid', 'Waived')),
  waived_reason TEXT,
  paid_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(meeting_id, resident_id)
);

ALTER TABLE meeting_fines ENABLE ROW LEVEL SECURITY;

-- 3. Meeting Comments / Q&A table
CREATE TABLE IF NOT EXISTS meeting_comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id INTEGER NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  comment_text TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE meeting_comments ENABLE ROW LEVEL SECURITY;

-- 4. Action items table enhancements (if needed)
ALTER TABLE meeting_actions ADD COLUMN IF NOT EXISTS responsible_person VARCHAR(255);
