ALTER TABLE notices
  ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'published',
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

DROP TRIGGER IF EXISTS notices_set_updated_at ON notices;
CREATE TRIGGER notices_set_updated_at
BEFORE UPDATE ON notices
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS notice_polls (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notice_id INTEGER NOT NULL UNIQUE REFERENCES notices(id) ON DELETE CASCADE,
  question TEXT NOT NULL,
  poll_type VARCHAR(20) NOT NULL DEFAULT 'yes_no'
    CHECK (poll_type IN ('yes_no', 'single_choice', 'multiple_choice')),
  start_at TIMESTAMPTZ NOT NULL,
  end_at TIMESTAMPTZ NOT NULL,
  anonymous BOOLEAN NOT NULL DEFAULT FALSE,
  allow_vote_change BOOLEAN NOT NULL DEFAULT FALSE,
  show_results_before_end BOOLEAN NOT NULL DEFAULT FALSE,
  mandatory BOOLEAN NOT NULL DEFAULT FALSE,
  closed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (end_at > start_at)
);

CREATE TABLE IF NOT EXISTS notice_poll_options (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id INTEGER NOT NULL REFERENCES notice_polls(id) ON DELETE CASCADE,
  option_text TEXT NOT NULL,
  order_index INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS notice_poll_votes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id INTEGER NOT NULL REFERENCES notice_polls(id) ON DELETE CASCADE,
  option_id INTEGER NOT NULL REFERENCES notice_poll_options(id) ON DELETE CASCADE,
  resident_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  flat_no VARCHAR(50),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (poll_id, option_id, resident_id)
);

CREATE INDEX IF NOT EXISTS idx_notice_polls_notice ON notice_polls(notice_id);
CREATE INDEX IF NOT EXISTS idx_notice_poll_votes_poll ON notice_poll_votes(poll_id);
CREATE INDEX IF NOT EXISTS idx_notice_poll_votes_resident ON notice_poll_votes(resident_id);

DROP TRIGGER IF EXISTS notice_polls_set_updated_at ON notice_polls;
CREATE TRIGGER notice_polls_set_updated_at
BEFORE UPDATE ON notice_polls
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS notice_poll_votes_set_updated_at ON notice_poll_votes;
CREATE TRIGGER notice_poll_votes_set_updated_at
BEFORE UPDATE ON notice_poll_votes
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
