ALTER TABLE users
  ADD COLUMN IF NOT EXISTS rules_accepted BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS rules_accepted_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS accepted_rules_version INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS society_rules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  category VARCHAR(50) NOT NULL DEFAULT 'General',
  display_order INTEGER NOT NULL DEFAULT 0,
  is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by INTEGER REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_society_rules_order ON society_rules(is_pinned DESC, display_order, id);
CREATE INDEX IF NOT EXISTS idx_society_rules_category ON society_rules(category);
CREATE INDEX IF NOT EXISTS idx_society_rules_active ON society_rules(is_active);

DROP TRIGGER IF EXISTS society_rules_set_updated_at ON society_rules;
CREATE TRIGGER society_rules_set_updated_at
BEFORE UPDATE ON society_rules
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

INSERT INTO app_settings (setting_key, setting_value)
VALUES ('rules_version', '1')
ON CONFLICT (setting_key) DO NOTHING;
