-- Migration 037: Financial Accounting & Reports Enhancements (Dual-Account Bank vs Cash)

-- 1. Add payment_account column to maintenance_expenses if it doesn't exist
ALTER TABLE maintenance_expenses
  ADD COLUMN IF NOT EXISTS payment_account VARCHAR(20) DEFAULT 'BANK';

ALTER TABLE maintenance_expenses
  DROP CONSTRAINT IF EXISTS maintenance_expenses_payment_account_check;

ALTER TABLE maintenance_expenses
  ADD CONSTRAINT maintenance_expenses_payment_account_check
  CHECK (payment_account IN ('BANK', 'CASH'));

-- 2. Add payment_account column to payments if it doesn't exist
ALTER TABLE payments
  ADD COLUMN IF NOT EXISTS payment_account VARCHAR(20) DEFAULT 'BANK';

ALTER TABLE payments
  DROP CONSTRAINT IF EXISTS payments_payment_account_check;

ALTER TABLE payments
  ADD CONSTRAINT payments_payment_account_check
  CHECK (payment_account IN ('BANK', 'CASH'));

-- 3. Populate payment_account based on payment_method for existing records
UPDATE maintenance_expenses
SET payment_account = CASE
  WHEN LOWER(COALESCE(payment_method, '')) LIKE '%cash%' THEN 'CASH'
  ELSE 'BANK'
END
WHERE payment_account IS NULL OR payment_account = 'BANK';

UPDATE payments
SET payment_account = CASE
  WHEN LOWER(COALESCE(payment_method, '')) LIKE '%cash%' THEN 'CASH'
  ELSE 'BANK'
END
WHERE payment_account IS NULL OR payment_account = 'BANK';

-- 4. Create society_opening_balances table for baseline Financial Year opening balances
CREATE TABLE IF NOT EXISTS society_opening_balances (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  financial_year VARCHAR(20) NOT NULL UNIQUE,
  bank_opening NUMERIC(14, 2) NOT NULL DEFAULT 0.00 CHECK (bank_opening >= 0),
  cash_opening NUMERIC(14, 2) NOT NULL DEFAULT 0.00 CHECK (cash_opening >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Seed default baseline opening balances as 0.00 if not present
INSERT INTO society_opening_balances (financial_year, bank_opening, cash_opening)
VALUES ('2026-2027', 0.00, 0.00)
ON CONFLICT (financial_year) DO NOTHING;

-- Create indexes for report queries
CREATE INDEX IF NOT EXISTS idx_payments_payment_account ON payments(payment_account);
CREATE INDEX IF NOT EXISTS idx_payments_payment_status ON payments(payment_status);
CREATE INDEX IF NOT EXISTS idx_maintenance_expenses_payment_account ON maintenance_expenses(payment_account);
CREATE INDEX IF NOT EXISTS idx_maintenance_expenses_status ON maintenance_expenses(status);

ALTER TABLE society_opening_balances ENABLE ROW LEVEL SECURITY;
