ALTER TABLE maintenance_expenses ADD COLUMN IF NOT EXISTS account_type VARCHAR(10);
UPDATE maintenance_expenses SET account_type = CASE WHEN LOWER(COALESCE(payment_method, '')) = 'cash' THEN 'CASH' ELSE 'BANK' END WHERE account_type IS NULL;
ALTER TABLE maintenance_expenses ALTER COLUMN account_type SET DEFAULT 'BANK';
ALTER TABLE maintenance_expenses ALTER COLUMN account_type SET NOT NULL;
ALTER TABLE maintenance_expenses DROP CONSTRAINT IF EXISTS maintenance_expenses_account_type_check;
ALTER TABLE maintenance_expenses ADD CONSTRAINT maintenance_expenses_account_type_check CHECK (account_type IN ('BANK', 'CASH'));

CREATE TABLE IF NOT EXISTS accounting_opening_balances (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  effective_date DATE NOT NULL UNIQUE,
  bank_amount NUMERIC(14,2) NOT NULL CHECK (bank_amount >= 0),
  cash_amount NUMERIC(14,2) NOT NULL CHECK (cash_amount >= 0),
  reason TEXT NOT NULL DEFAULT 'Initial accounting balance',
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_accounting_opening_date ON accounting_opening_balances(effective_date);
CREATE INDEX IF NOT EXISTS idx_report_maintenance_payment ON maintenance(payment_date,status);
CREATE INDEX IF NOT EXISTS idx_report_expense_account ON maintenance_expenses(account_type,expense_date,status);
ALTER TABLE accounting_opening_balances ENABLE ROW LEVEL SECURITY;
