-- Migration 038: Monthly Maintenance Report Module & Ledger System

-- 1. Ensure fields on maintenance table
ALTER TABLE maintenance
  ADD COLUMN IF NOT EXISTS penalty NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS discount_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS write_off_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS advance_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS total_payable NUMERIC(12, 2);

UPDATE maintenance
SET
  penalty = COALESCE(penalty, 0.00),
  discount_amount = COALESCE(discount_amount, 0.00),
  write_off_amount = COALESCE(write_off_amount, 0.00),
  advance_amount = COALESCE(advance_amount, 0.00),
  total_payable = COALESCE(total_payable, total_amount, GREATEST(COALESCE(amount, 0) + COALESCE(penalty, 0) - COALESCE(discount_amount, 0) - COALESCE(write_off_amount, 0), 0))
WHERE total_payable IS NULL OR penalty IS NULL OR discount_amount IS NULL OR write_off_amount IS NULL;

-- 2. Ensure fields on payments table
ALTER TABLE payments
  ADD COLUMN IF NOT EXISTS resident_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS rejection_reason TEXT,
  ADD COLUMN IF NOT EXISTS rejected_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS rejected_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS verified_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS receipt_number VARCHAR(80);

-- 3. Create or update maintenance_writeoffs table
CREATE TABLE IF NOT EXISTS maintenance_writeoffs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_id INTEGER NOT NULL REFERENCES maintenance(id) ON DELETE CASCADE,
  resident_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  flat_id INTEGER REFERENCES flats(id) ON DELETE SET NULL,
  admin_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  admin_name VARCHAR(255),
  writeoff_type VARCHAR(50) NOT NULL,
  amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
  reason VARCHAR(255),
  remarks TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Create ledger_transactions table
CREATE TABLE IF NOT EXISTS ledger_transactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resident_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  transaction_type VARCHAR(60) NOT NULL,
  credit NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  debit NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  balance NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  reference_id INTEGER,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ledger_resident_id ON ledger_transactions(resident_id);
CREATE INDEX IF NOT EXISTS idx_ledger_created_at ON ledger_transactions(created_at);

ALTER TABLE ledger_transactions ENABLE ROW LEVEL SECURITY;
