-- Migration 040: Dedicated Maintenance Billing Cycle System
-- Adds maintenance_billing_cycles table as the authoritative source for monthly bill generation.
-- Also links billing_cycle_id to maintenance table for traceability.

-- Create the billing cycles table
CREATE TABLE IF NOT EXISTS maintenance_billing_cycles (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  society_id          INTEGER NOT NULL DEFAULT 1,
  billing_month       INTEGER NOT NULL CHECK (billing_month BETWEEN 1 AND 12),
  billing_year        INTEGER NOT NULL CHECK (billing_year >= 2000),
  billing_period_key  VARCHAR(20) GENERATED ALWAYS AS (
                        LPAD(billing_year::text, 4, '0') || '-' || LPAD(billing_month::text, 2, '0')
                      ) STORED,
  billing_status      VARCHAR(30) NOT NULL DEFAULT 'GENERATED'
                        CHECK (billing_status IN ('DRAFT','GENERATING','GENERATED','FAILED','CANCELLED')),
  total_residents     INTEGER NOT NULL DEFAULT 0,
  generated_bill_count INTEGER NOT NULL DEFAULT 0,
  grace_period_days   INTEGER NOT NULL DEFAULT 10,
  due_date            DATE NOT NULL,
  penalty_start_date  DATE NOT NULL,
  settings_snapshot   JSONB,
  generated_by        INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_billing_cycle UNIQUE (society_id, billing_year, billing_month)
);

-- Index for quick society + period lookups
CREATE INDEX IF NOT EXISTS idx_billing_cycles_society_period
  ON maintenance_billing_cycles (society_id, billing_year DESC, billing_month DESC);

-- Add billing_cycle_id FK to maintenance table (nullable: manual/legacy bills without cycle)
ALTER TABLE maintenance
  ADD COLUMN IF NOT EXISTS billing_cycle_id BIGINT
  REFERENCES maintenance_billing_cycles(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_maintenance_billing_cycle
  ON maintenance (billing_cycle_id);

-- Add bill_type column for distinguishing maintenance vs manual vs other
ALTER TABLE maintenance
  ADD COLUMN IF NOT EXISTS bill_type VARCHAR(30) DEFAULT 'maintenance';

-- Update auto-timestamp trigger for billing cycles
CREATE OR REPLACE FUNCTION update_billing_cycles_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_billing_cycles_updated_at ON maintenance_billing_cycles;
CREATE TRIGGER trg_billing_cycles_updated_at
  BEFORE UPDATE ON maintenance_billing_cycles
  FOR EACH ROW EXECUTE FUNCTION update_billing_cycles_updated_at();
