-- Migration 041: shared-schema multi-tenant foundation.
-- Existing production data is preserved under Mahalaxmi (tenant id 1).

-- Managed PostgreSQL connection strings commonly use a table owner or a role
-- with BYPASSRLS. Requests switch to this deliberately unprivileged role so
-- FORCE RLS remains effective even on those deployments.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'society_tenant_app') THEN
    CREATE ROLE society_tenant_app NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  END IF;
END $$;
GRANT society_tenant_app TO CURRENT_USER;

CREATE TABLE IF NOT EXISTS societies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  code VARCHAR(24) NOT NULL UNIQUE,
  logo_url TEXT,
  address TEXT,
  city VARCHAR(120),
  state VARCHAR(120),
  pincode VARCHAR(12),
  contact_email VARCHAR(255),
  contact_phone VARCHAR(30),
  registration_number VARCHAR(120),
  status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO societies (id, name, code, city, state, status)
VALUES
  (1, 'Mahalaxmi Co-op Housing Society', 'MHLX', 'Mumbai', 'Maharashtra', 'active'),
  (2, 'Vighnaharta Co-op Housing Society', 'VIGH', 'Mumbai', 'Maharashtra', 'active')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  code = EXCLUDED.code,
  updated_at = NOW();

SELECT setval(
  pg_get_serial_sequence('societies', 'id'),
  GREATEST((SELECT COALESCE(MAX(id), 2) FROM societies), 2),
  true
);

CREATE OR REPLACE FUNCTION app_current_society_id()
RETURNS BIGINT
LANGUAGE sql
STABLE
AS $$
  SELECT NULLIF(current_setting('app.current_society_id', true), '')::BIGINT
$$;

CREATE OR REPLACE FUNCTION app_tenant_bypass()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
AS $$
  SELECT COALESCE(current_setting('app.tenant_bypass', true), '') = 'on'
$$;

-- Direct tenant keys are used on security boundaries and high-volume module
-- roots. Child rows also receive a key so RLS protects accidental unscoped
-- joins, updates and deletes at the database boundary.
DO $$
DECLARE
  table_name TEXT;
  tenant_tables TEXT[] := ARRAY[
    'users','flats','flat_types','resident_flat_assignments','flat_transfer_history',
    'maintenance','maintenance_bills','maintenance_bill_items','maintenance_categories',
    'resident_maintenance_categories','flat_category_assignments','maintenance_settings',
    'late_fee_rules','maintenance_expenses','maintenance_disputes','maintenance_audit_logs',
    'maintenance_writeoffs','write_offs','maintenance_billing_cycles','billing_cycle_locks',
    'billing_override_audit_log','payments','payment_maintenance','payment_status_history',
    'ledger_transactions','accounting_opening_balances','society_opening_balances',
    'complaints','complaint_audit_logs','notices','notice_polls','notice_poll_options',
    'notice_poll_votes','events','meetings','meeting_agendas','meeting_attendance',
    'meeting_reports','meeting_actions','meeting_votes','meeting_resident_votes',
    'meeting_documents','meeting_fines','meeting_comments','noc_types','noc_requests',
    'noc_audit_logs','society_rules','society_rule_acknowledgements','notifications',
    'admin_notification_reads','staff','visitors','parcels','activities','app_settings',
    'password_reset_tokens'
  ];
BEGIN
  FOREACH table_name IN ARRAY tenant_tables LOOP
    IF to_regclass('public.' || table_name) IS NOT NULL THEN
      EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS society_id BIGINT', table_name);
      EXECUTE format('UPDATE %I SET society_id = 1 WHERE society_id IS NULL', table_name);
      EXECUTE format('ALTER TABLE %I ALTER COLUMN society_id SET DEFAULT app_current_society_id()', table_name);
      EXECUTE format('ALTER TABLE %I ALTER COLUMN society_id SET NOT NULL', table_name);
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = to_regclass('public.' || table_name)
          AND conname = table_name || '_society_id_fkey'
      ) THEN
        EXECUTE format(
          'ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE RESTRICT',
          table_name, table_name || '_society_id_fkey'
        );
      END IF;
      EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I (society_id)', 'idx_' || table_name || '_society', table_name);
    END IF;
  END LOOP;
END $$;

-- Tenant-scoped natural keys. Both societies may have Wing A / Flat 101.
ALTER TABLE flats DROP CONSTRAINT IF EXISTS flats_wing_flat_no_key;
CREATE UNIQUE INDEX IF NOT EXISTS uq_flats_society_wing_number
  ON flats (society_id, COALESCE(wing, wing_block, ''), flat_no);

ALTER TABLE flat_types DROP CONSTRAINT IF EXISTS flat_types_name_key;
ALTER TABLE maintenance_categories DROP CONSTRAINT IF EXISTS maintenance_categories_name_key;
ALTER TABLE noc_types DROP CONSTRAINT IF EXISTS noc_types_name_key;
CREATE UNIQUE INDEX IF NOT EXISTS uq_flat_types_society_name
  ON flat_types (society_id, LOWER(name));
CREATE UNIQUE INDEX IF NOT EXISTS uq_maintenance_categories_society_name
  ON maintenance_categories (society_id, LOWER(name));
CREATE UNIQUE INDEX IF NOT EXISTS uq_noc_types_society_name
  ON noc_types (society_id, LOWER(name));
-- Historical deployments can contain multiple settings revisions. Keep them
-- tenant-isolated without deleting history; controllers select the latest row.
CREATE INDEX IF NOT EXISTS idx_maintenance_settings_society_created
  ON maintenance_settings (society_id, created_at DESC);
ALTER TABLE society_opening_balances DROP CONSTRAINT IF EXISTS society_opening_balances_financial_year_key;
CREATE UNIQUE INDEX IF NOT EXISTS uq_society_opening_balance_year
  ON society_opening_balances (society_id, financial_year);
ALTER TABLE accounting_opening_balances DROP CONSTRAINT IF EXISTS accounting_opening_balances_effective_date_key;
CREATE UNIQUE INDEX IF NOT EXISTS uq_accounting_opening_balance_date
  ON accounting_opening_balances (society_id, effective_date);
ALTER TABLE maintenance_expenses DROP CONSTRAINT IF EXISTS maintenance_expenses_expense_number_key;
CREATE UNIQUE INDEX IF NOT EXISTS uq_maintenance_expense_number
  ON maintenance_expenses (society_id, expense_number);
ALTER TABLE noc_requests DROP CONSTRAINT IF EXISTS noc_requests_request_number_key;
CREATE UNIQUE INDEX IF NOT EXISTS uq_noc_request_number
  ON noc_requests (society_id, request_number);

-- app_settings previously used setting_key as a global primary key. Give it a
-- surrogate key and scope the natural key to the tenant.
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE app_settings DROP CONSTRAINT IF EXISTS app_settings_pkey;
ALTER TABLE app_settings ADD CONSTRAINT app_settings_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_app_settings_society_key
  ON app_settings (society_id, setting_key);

CREATE INDEX IF NOT EXISTS idx_users_society_role_status ON users (society_id, role, status);
CREATE INDEX IF NOT EXISTS idx_flats_society_status ON flats (society_id, status);
CREATE INDEX IF NOT EXISTS idx_maintenance_society_period ON maintenance (society_id, year, month);
CREATE INDEX IF NOT EXISTS idx_payments_society_status_created ON payments (society_id, payment_status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_complaints_society_status_created ON complaints (society_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_society_resident_created ON notifications (society_id, resident_id, created_at DESC);

-- The two-key foreign keys below prevent the most dangerous cross-tenant
-- references even if application validation regresses.
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_id_society ON users (id, society_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_flats_id_society ON flats (id, society_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_maintenance_id_society ON maintenance (id, society_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_complaints_id_society ON complaints (id, society_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_meetings_id_society ON meetings (id, society_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_notices_id_society ON notices (id, society_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_noc_requests_id_society ON noc_requests (id, society_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_society_rules_id_society ON society_rules (id, society_id);

CREATE OR REPLACE FUNCTION add_tenant_fk(
  child_table TEXT,
  child_column TEXT,
  parent_table TEXT,
  constraint_name TEXT
) RETURNS VOID LANGUAGE plpgsql AS $$
BEGIN
  IF to_regclass('public.' || child_table) IS NULL OR to_regclass('public.' || parent_table) IS NULL THEN RETURN; END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = child_table AND column_name = child_column
  ) THEN RETURN; END IF;
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = constraint_name AND conrelid = to_regclass('public.' || child_table)) THEN RETURN; END IF;
  EXECUTE format(
    'ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY (%I, society_id) REFERENCES %I(id, society_id) ON DELETE RESTRICT',
    child_table, constraint_name, child_column, parent_table
  );
END $$;

SELECT add_tenant_fk('users', 'flat_id', 'flats', 'fk_users_flat_tenant');
SELECT add_tenant_fk('flats', 'current_resident_id', 'users', 'fk_flats_resident_tenant');
SELECT add_tenant_fk('maintenance', 'resident_id', 'users', 'fk_maintenance_resident_tenant');
SELECT add_tenant_fk('maintenance', 'flat_id', 'flats', 'fk_maintenance_flat_tenant');
SELECT add_tenant_fk('maintenance_bills', 'resident_id', 'users', 'fk_maintenance_bills_resident_tenant');
SELECT add_tenant_fk('maintenance_bills', 'flat_id', 'flats', 'fk_maintenance_bills_flat_tenant');
SELECT add_tenant_fk('payments', 'resident_id', 'users', 'fk_payments_resident_tenant');
SELECT add_tenant_fk('payments', 'bill_id', 'maintenance', 'fk_payments_bill_tenant');
SELECT add_tenant_fk('complaints', 'user_id', 'users', 'fk_complaints_user_tenant');
SELECT add_tenant_fk('notifications', 'resident_id', 'users', 'fk_notifications_resident_tenant');
SELECT add_tenant_fk('noc_requests', 'resident_id', 'users', 'fk_noc_resident_tenant');
SELECT add_tenant_fk('noc_requests', 'flat_id', 'flats', 'fk_noc_flat_tenant');
SELECT add_tenant_fk('meeting_attendance', 'meeting_id', 'meetings', 'fk_attendance_meeting_tenant');
SELECT add_tenant_fk('meeting_attendance', 'resident_id', 'users', 'fk_attendance_resident_tenant');
SELECT add_tenant_fk('meeting_actions', 'meeting_id', 'meetings', 'fk_meeting_actions_tenant');
SELECT add_tenant_fk('meeting_reports', 'meeting_id', 'meetings', 'fk_meeting_reports_tenant');
SELECT add_tenant_fk('society_rule_acknowledgements', 'rule_id', 'society_rules', 'fk_rule_ack_rule_tenant');
SELECT add_tenant_fk('society_rule_acknowledgements', 'resident_id', 'users', 'fk_rule_ack_resident_tenant');
DROP FUNCTION add_tenant_fk(TEXT, TEXT, TEXT, TEXT);

-- Database-enforced tenant isolation. FORCE also protects against accidental
-- unscoped queries executed by the table owner used by this application.
DO $$
DECLARE
  table_name TEXT;
BEGIN
  FOR table_name IN
    SELECT c.table_name
    FROM information_schema.columns c
    JOIN information_schema.tables t
      ON t.table_schema = c.table_schema AND t.table_name = c.table_name
    WHERE c.table_schema = 'public' AND c.column_name = 'society_id' AND t.table_type = 'BASE TABLE'
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', table_name);
    EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I', table_name);
    EXECUTE format(
      'CREATE POLICY tenant_isolation ON %I USING (society_id = app_current_society_id() OR app_tenant_bypass()) WITH CHECK (society_id = app_current_society_id() OR app_tenant_bypass())',
      table_name
    );
  END LOOP;
END $$;

ALTER TABLE societies ENABLE ROW LEVEL SECURITY;
ALTER TABLE societies FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON societies;
CREATE POLICY tenant_isolation ON societies
  USING (id = app_current_society_id() OR app_tenant_bypass())
  WITH CHECK (id = app_current_society_id() OR app_tenant_bypass());

GRANT USAGE ON SCHEMA public TO society_tenant_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO society_tenant_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO society_tenant_app;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO society_tenant_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO society_tenant_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO society_tenant_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT EXECUTE ON FUNCTIONS TO society_tenant_app;
