-- Secure, tenant-scoped Excel transaction import staging and audit trail.
CREATE TABLE IF NOT EXISTS excel_transaction_import_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  society_id BIGINT NOT NULL DEFAULT app_current_society_id() REFERENCES societies(id) ON DELETE RESTRICT,
  created_by INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  file_name VARCHAR(255) NOT NULL,
  file_fingerprint CHAR(64) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PREVIEWED'
    CHECK (status IN ('PREVIEWED', 'IMPORTING', 'COMPLETED', 'FAILED')),
  total_rows INTEGER NOT NULL DEFAULT 0 CHECK (total_rows >= 0),
  valid_rows INTEGER NOT NULL DEFAULT 0 CHECK (valid_rows >= 0),
  invalid_rows INTEGER NOT NULL DEFAULT 0 CHECK (invalid_rows >= 0),
  warning_rows INTEGER NOT NULL DEFAULT 0 CHECK (warning_rows >= 0),
  total_valid_amount NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (total_valid_amount >= 0),
  imported_rows INTEGER NOT NULL DEFAULT 0 CHECK (imported_rows >= 0),
  skipped_rows INTEGER NOT NULL DEFAULT 0 CHECK (skipped_rows >= 0),
  failed_rows INTEGER NOT NULL DEFAULT 0 CHECK (failed_rows >= 0),
  confirmed_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (society_id, file_fingerprint)
);

CREATE TABLE IF NOT EXISTS excel_transaction_import_rows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  society_id BIGINT NOT NULL DEFAULT app_current_society_id() REFERENCES societies(id) ON DELETE RESTRICT,
  batch_id BIGINT NOT NULL REFERENCES excel_transaction_import_batches(id) ON DELETE CASCADE,
  row_number INTEGER NOT NULL CHECK (row_number >= 2),
  row_fingerprint CHAR(64) NOT NULL,
  transaction_id INTEGER REFERENCES payments(id) ON DELETE SET NULL,
  member_id INTEGER,
  member_name VARCHAR(255),
  wing VARCHAR(80),
  flat_number VARCHAR(80),
  bill_id INTEGER,
  transaction_date DATE,
  transaction_type VARCHAR(50),
  payment_mode VARCHAR(50),
  amount NUMERIC(14, 2),
  reference_number VARCHAR(255),
  payment_status VARCHAR(40),
  remarks TEXT,
  import_action VARCHAR(10),
  validation_result VARCHAR(10) NOT NULL CHECK (validation_result IN ('VALID', 'INVALID', 'WARNING')),
  validation_message TEXT,
  imported_payment_id INTEGER REFERENCES payments(id) ON DELETE SET NULL,
  imported_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (batch_id, row_number)
);

CREATE INDEX IF NOT EXISTS idx_excel_batches_society_created
  ON excel_transaction_import_batches (society_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_excel_batches_id_society
  ON excel_transaction_import_batches (id, society_id);
CREATE INDEX IF NOT EXISTS idx_excel_rows_batch_result
  ON excel_transaction_import_rows (batch_id, validation_result, row_number);
CREATE INDEX IF NOT EXISTS idx_excel_rows_society_fingerprint
  ON excel_transaction_import_rows (society_id, row_fingerprint);

ALTER TABLE excel_transaction_import_rows
  DROP CONSTRAINT IF EXISTS fk_excel_rows_batch_tenant;
ALTER TABLE excel_transaction_import_rows
  ADD CONSTRAINT fk_excel_rows_batch_tenant
  FOREIGN KEY (batch_id, society_id)
  REFERENCES excel_transaction_import_batches(id, society_id)
  ON DELETE CASCADE;

ALTER TABLE excel_transaction_import_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE excel_transaction_import_batches FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON excel_transaction_import_batches;
CREATE POLICY tenant_isolation ON excel_transaction_import_batches
  USING (society_id = app_current_society_id() OR app_tenant_bypass())
  WITH CHECK (society_id = app_current_society_id() OR app_tenant_bypass());

ALTER TABLE excel_transaction_import_rows ENABLE ROW LEVEL SECURITY;
ALTER TABLE excel_transaction_import_rows FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON excel_transaction_import_rows;
CREATE POLICY tenant_isolation ON excel_transaction_import_rows
  USING (society_id = app_current_society_id() OR app_tenant_bypass())
  WITH CHECK (society_id = app_current_society_id() OR app_tenant_bypass());

GRANT SELECT, INSERT, UPDATE, DELETE ON excel_transaction_import_batches TO society_tenant_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON excel_transaction_import_rows TO society_tenant_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO society_tenant_app;
