ALTER TABLE users ADD COLUMN IF NOT EXISTS ownership_type VARCHAR(10);
ALTER TABLE users ADD COLUMN IF NOT EXISTS occupancy_status VARCHAR(10);

DO $$ BEGIN
  ALTER TABLE users ADD CONSTRAINT users_ownership_type_check CHECK (ownership_type IS NULL OR ownership_type IN ('Owner', 'Tenant'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE users ADD CONSTRAINT users_occupancy_status_check CHECK (occupancy_status IS NULL OR occupancy_status IN ('Active', 'Inactive'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS resident_import_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  society_id BIGINT NOT NULL DEFAULT app_current_society_id() REFERENCES societies(id) ON DELETE RESTRICT,
  created_by INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  file_name VARCHAR(255) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PREVIEWED' CHECK (status IN ('PREVIEWED','COMPLETED','FAILED')),
  total_rows INTEGER NOT NULL DEFAULT 0,
  valid_rows INTEGER NOT NULL DEFAULT 0,
  invalid_rows INTEGER NOT NULL DEFAULT 0,
  duplicate_rows INTEGER NOT NULL DEFAULT 0,
  imported_rows INTEGER NOT NULL DEFAULT 0,
  skipped_rows INTEGER NOT NULL DEFAULT 0,
  failed_rows INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS resident_import_rows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  society_id BIGINT NOT NULL DEFAULT app_current_society_id() REFERENCES societies(id) ON DELETE RESTRICT,
  batch_id BIGINT NOT NULL REFERENCES resident_import_batches(id) ON DELETE CASCADE,
  row_number INTEGER NOT NULL,
  flat_number VARCHAR(50), resident_name VARCHAR(255), email VARCHAR(255), mobile_number VARCHAR(20),
  flat_type VARCHAR(120), ownership_type VARCHAR(10), occupancy_status VARCHAR(10),
  validation_result VARCHAR(12) NOT NULL CHECK (validation_result IN ('VALID','INVALID','DUPLICATE')),
  validation_message TEXT,
  imported_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(batch_id, row_number)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_resident_import_batches_id_society ON resident_import_batches(id, society_id);
CREATE INDEX IF NOT EXISTS idx_resident_import_rows_batch ON resident_import_rows(batch_id, validation_result, row_number);
ALTER TABLE resident_import_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE resident_import_batches FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON resident_import_batches;
CREATE POLICY tenant_isolation ON resident_import_batches USING (society_id = app_current_society_id() OR app_tenant_bypass()) WITH CHECK (society_id = app_current_society_id() OR app_tenant_bypass());
ALTER TABLE resident_import_rows ENABLE ROW LEVEL SECURITY;
ALTER TABLE resident_import_rows FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON resident_import_rows;
CREATE POLICY tenant_isolation ON resident_import_rows USING (society_id = app_current_society_id() OR app_tenant_bypass()) WITH CHECK (society_id = app_current_society_id() OR app_tenant_bypass());
GRANT SELECT, INSERT, UPDATE, DELETE ON resident_import_batches, resident_import_rows TO society_tenant_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO society_tenant_app;
