const { promisePool } = require('../config/database');

let pollSchemaReady = false;

const toBool = (value) => value === true || value === 'true' || value === 1 || value === '1';
const asArray = (value) => Array.isArray(value) ? value : [];
const normalizeDateTime = (value) => {
  if (!value) return value;
  if (value instanceof Date) return value.toISOString();
  const text = String(value);
  if (/[zZ]$|[+-]\d{2}:\d{2}$/.test(text)) return text;
  return new Date(text).toISOString();
};

const ensurePollSchema = async () => {
  if (pollSchemaReady) return;
  await promisePool.query(`ALTER TABLE notices ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'published'`);
  await promisePool.query(`ALTER TABLE notices ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`);
  await promisePool.query(`
    CREATE TABLE IF NOT EXISTS notice_polls (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      notice_id INTEGER NOT NULL UNIQUE REFERENCES notices(id) ON DELETE CASCADE,
      question TEXT NOT NULL,
      poll_type VARCHAR(20) NOT NULL DEFAULT 'yes_no',
      start_at TIMESTAMPTZ NOT NULL,
      end_at TIMESTAMPTZ NOT NULL,
      anonymous BOOLEAN NOT NULL DEFAULT FALSE,
      allow_vote_change BOOLEAN NOT NULL DEFAULT FALSE,
      show_results_before_end BOOLEAN NOT NULL DEFAULT FALSE,
      mandatory BOOLEAN NOT NULL DEFAULT FALSE,
      closed_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await promisePool.query(`
    CREATE TABLE IF NOT EXISTS notice_poll_options (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      poll_id INTEGER NOT NULL REFERENCES notice_polls(id) ON DELETE CASCADE,
      option_text TEXT NOT NULL,
      order_index INTEGER NOT NULL DEFAULT 0
    )
  `);
  await promisePool.query(`
    CREATE TABLE IF NOT EXISTS notice_poll_votes (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      poll_id INTEGER NOT NULL REFERENCES notice_polls(id) ON DELETE CASCADE,
      option_id INTEGER NOT NULL REFERENCES notice_poll_options(id) ON DELETE CASCADE,
      resident_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      flat_no VARCHAR(50),
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      UNIQUE (poll_id, option_id, resident_id)
    )
  `);
  pollSchemaReady = true;
};

const pollStatus = (poll) => {
  if (!poll) return 'No Poll';
  const now = Date.now();
  if (poll.closed_at || now > new Date(poll.end_at).getTime()) return 'Poll Closed';
  if (now < new Date(poll.start_at).getTime()) return 'Upcoming Poll';
  return 'Poll Active';
};

const canShowResults = (poll, userRole) => {
  if (!poll) return false;
  return userRole === 'admin' || poll.show_results_before_end || pollStatus(poll) === 'Poll Closed';
};

const eligibleResidentCount = async () => {
  const [rows] = await promisePool.query(
    "SELECT COUNT(*)::int AS count FROM users WHERE role = 'resident' AND COALESCE(status, 'approved') = 'approved'"
  );
  return Number(rows[0]?.count || 0);
};

const buildResults = async (pollId, eligibleCount, includeVoters) => {
  const [options] = await promisePool.query(
    `SELECT o.id, o.option_text, o.order_index, COUNT(v.id)::int AS votes
     FROM notice_poll_options o
     LEFT JOIN notice_poll_votes v ON v.option_id = o.id
     WHERE o.poll_id = ?
     GROUP BY o.id, o.option_text, o.order_index
     ORDER BY o.order_index, o.id`,
    [pollId]
  );
  const [voteRows] = await promisePool.query(
    'SELECT COUNT(DISTINCT resident_id)::int AS votes_cast FROM notice_poll_votes WHERE poll_id = ?',
    [pollId]
  );
  const votesCast = Number(voteRows[0]?.votes_cast || 0);
  const maxVotes = Math.max(...options.map((option) => Number(option.votes || 0)), 0);
  const winning = options.filter((option) => Number(option.votes || 0) === maxVotes && maxVotes > 0).map((option) => option.option_text);
  let voters = [];

  if (includeVoters) {
    const [voterRows] = await promisePool.query(
      `SELECT DISTINCT v.resident_id, u.name AS resident_name, COALESCE(v.flat_no, f.flat_no) AS flat_no, MAX(v.updated_at) AS vote_timestamp
       FROM notice_poll_votes v
       JOIN users u ON u.id = v.resident_id
       LEFT JOIN flats f ON f.id = u.flat_id
       WHERE v.poll_id = ?
       GROUP BY v.resident_id, u.name, COALESCE(v.flat_no, f.flat_no)
       ORDER BY MAX(v.updated_at) DESC`,
      [pollId]
    );
    voters = voterRows;
  }

  return {
    total_eligible: eligibleCount,
    votes_cast: votesCast,
    participation_percent: eligibleCount ? Math.round((votesCast / eligibleCount) * 100) : 0,
    winning_option: winning.length ? winning.join(', ') : 'No votes yet',
    options: options.map((option) => ({
      ...option,
      votes: Number(option.votes || 0),
      percent: votesCast ? Math.round((Number(option.votes || 0) / votesCast) * 100) : 0
    })),
    voters
  };
};

const attachPolls = async (notices, user = {}) => {
  await ensurePollSchema();
  const list = Array.isArray(notices) ? notices : [notices];
  if (!list.length) return notices;
  const eligible = await eligibleResidentCount();

  for (const notice of list) {
    const [polls] = await promisePool.query('SELECT * FROM notice_polls WHERE notice_id = ?', [notice.id]);
    const poll = polls[0] || null;
    notice.poll_status = pollStatus(poll);
    notice.has_poll = Boolean(poll);
    if (!poll) continue;

    const [options] = await promisePool.query(
      'SELECT id, option_text, order_index FROM notice_poll_options WHERE poll_id = ? ORDER BY order_index, id',
      [poll.id]
    );
    const [myVotes] = user.id
      ? await promisePool.query('SELECT option_id FROM notice_poll_votes WHERE poll_id = ? AND resident_id = ?', [poll.id, user.id])
      : [[]];

    poll.options = options;
    poll.status = notice.poll_status;
    poll.my_vote_option_ids = myVotes.map((vote) => vote.option_id);
    poll.results_visible = canShowResults(poll, user.role);
    if (poll.results_visible) {
      poll.results = await buildResults(poll.id, eligible, user.role === 'admin' && !poll.anonymous);
    }
    notice.poll = poll;
  }

  return Array.isArray(notices) ? list : list[0];
};

const validatePollPayload = (poll) => {
  if (!poll?.enabled) return null;
  const options = asArray(poll.options).map((option) => String(option.option_text || option).trim()).filter(Boolean);
  if (!poll.question || !poll.start_at || !poll.end_at) return 'Poll question, start time and end time are required';
  if (!['yes_no', 'single_choice', 'multiple_choice'].includes(poll.poll_type)) return 'Invalid poll type';
  if (options.length < 2 || options.length > 10) return 'Poll options must be between 2 and 10';
  if (new Date(normalizeDateTime(poll.end_at)) <= new Date(normalizeDateTime(poll.start_at))) return 'Poll end time must be after start time';
  return null;
};

const savePoll = async (connection, noticeId, poll) => {
  await connection.query('DELETE FROM notice_polls WHERE notice_id = ?', [noticeId]);
  if (!poll?.enabled) return;

  const validation = validatePollPayload(poll);
  if (validation) throw new Error(validation);

  const [pollInsert] = await connection.query(
    `INSERT INTO notice_polls
      (notice_id, question, poll_type, start_at, end_at, anonymous, allow_vote_change, show_results_before_end, mandatory)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    [
      noticeId,
      poll.question,
      poll.poll_type,
      normalizeDateTime(poll.start_at),
      normalizeDateTime(poll.end_at),
      toBool(poll.anonymous),
      toBool(poll.allow_vote_change),
      toBool(poll.show_results_before_end),
      toBool(poll.mandatory)
    ]
  );

  const pollId = pollInsert.insertId;
  const options = asArray(poll.options).map((option) => String(option.option_text || option).trim()).filter(Boolean);
  for (let index = 0; index < options.length; index += 1) {
    await connection.query(
      'INSERT INTO notice_poll_options (poll_id, option_text, order_index) VALUES (?, ?, ?)',
      [pollId, options[index], index]
    );
  }
};

const notifyResidents = async (title, message, referenceId) => {
  try {
    await promisePool.query(
      `INSERT INTO notifications (resident_id, title, message, type, reference_id, is_read)
       SELECT id, ?, ?, 'notice', ?, false
       FROM users
       WHERE role = 'resident' AND COALESCE(status, 'approved') = 'approved'`,
      [title, message, referenceId]
    );
  } catch (error) {
    console.error('Notice notification failed:', error);
  }
};

const sendPollTimelineNotifications = async () => {
  try {
    await promisePool.query(`
      INSERT INTO notifications (resident_id, title, message, type, reference_id, is_read)
      SELECT u.id,
             'Poll closing soon: ' || n.title,
             'This notice poll is closing within 24 hours. Please vote before it ends.',
             'notice',
             n.id,
             false
      FROM notice_polls p
      JOIN notices n ON n.id = p.notice_id
      JOIN users u ON u.role = 'resident' AND COALESCE(u.status, 'approved') = 'approved'
      LEFT JOIN notifications existing
        ON existing.resident_id = u.id
       AND existing.reference_id = n.id
       AND existing.title = 'Poll closing soon: ' || n.title
      WHERE p.closed_at IS NULL
        AND NOW() BETWEEN p.start_at AND p.end_at
        AND p.end_at <= NOW() + INTERVAL '24 hours'
        AND existing.id IS NULL
    `);

    await promisePool.query(`
      INSERT INTO notifications (resident_id, title, message, type, reference_id, is_read)
      SELECT u.id,
             'Poll ended: ' || n.title,
             'The notice poll has ended. Results are now available in the notice board.',
             'notice',
             n.id,
             false
      FROM notice_polls p
      JOIN notices n ON n.id = p.notice_id
      JOIN users u ON u.role = 'resident' AND COALESCE(u.status, 'approved') = 'approved'
      LEFT JOIN notifications existing
        ON existing.resident_id = u.id
       AND existing.reference_id = n.id
       AND existing.title = 'Poll ended: ' || n.title
      WHERE (p.closed_at IS NOT NULL OR NOW() > p.end_at)
        AND existing.id IS NULL
    `);
  } catch (error) {
    console.error('Poll timeline notification failed:', error);
  }
};

const getAllNotices = async (req, res) => {
  try {
    await ensurePollSchema();
    await sendPollTimelineNotifications();
    const filter = req.query.filter || 'all';
    const [notices] = await promisePool.query('SELECT * FROM notices ORDER BY created_at DESC');
    const withPolls = await attachPolls(notices, req.user);
    const filtered = withPolls.filter((notice) => {
      if (filter === 'with_polls') return notice.has_poll;
      if (filter === 'active_polls') return notice.poll_status === 'Poll Active';
      if (filter === 'closed_polls') return notice.poll_status === 'Poll Closed';
      return true;
    });
    res.json(filtered);
  } catch (error) {
    console.error('Get notices error:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

const getLatestNotices = async (req, res) => {
  try {
    await ensurePollSchema();
    await sendPollTimelineNotifications();
    const [notices] = await promisePool.query('SELECT * FROM notices ORDER BY created_at DESC LIMIT 5');
    res.json(await attachPolls(notices, req.user));
  } catch (error) {
    console.error('Get latest notices error:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

const getNoticeById = async (req, res) => {
  try {
    await ensurePollSchema();
    await sendPollTimelineNotifications();
    const { id } = req.params;
    const [notices] = await promisePool.query('SELECT * FROM notices WHERE id = ?', [id]);
    if (notices.length === 0) return res.status(404).json({ message: 'Notice not found' });
    res.json(await attachPolls(notices[0], req.user));
  } catch (error) {
    console.error('Get notice error:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

const createNotice = async (req, res) => {
  const connection = await promisePool.getConnection();
  try {
    await ensurePollSchema();
    const { title, description, poll } = req.body;
    if (!title || !description) return res.status(400).json({ message: 'Title and description are required' });

    await connection.beginTransaction();
    const [result] = await connection.query(
      'INSERT INTO notices (title, description, status) VALUES (?, ?, ?)',
      [title, description, 'published']
    );
    await savePoll(connection, result.insertId, poll);
    await connection.commit();

    await notifyResidents(
      poll?.enabled ? `New notice with poll: ${title}` : title,
      poll?.enabled ? (poll.question || 'A new poll is available in the notice board.') : (description || 'New society notice'),
      result.insertId
    );

    res.status(201).json({ id: result.insertId, title, description });
  } catch (error) {
    await connection.rollback();
    console.error('Create notice error:', error);
    res.status(500).json({ message: error.message || 'Server error' });
  } finally {
    connection.release();
  }
};

const updateNotice = async (req, res) => {
  const connection = await promisePool.getConnection();
  try {
    await ensurePollSchema();
    const { id } = req.params;
    const { title, description, poll } = req.body;
    if (!title || !description) return res.status(400).json({ message: 'Title and description are required' });

    await connection.beginTransaction();
    const [updated] = await connection.query(
      'UPDATE notices SET title = ?, description = ?, updated_at = NOW() WHERE id = ?',
      [title, description, id]
    );
    if (!updated.affectedRows) {
      await connection.rollback();
      return res.status(404).json({ message: 'Notice not found' });
    }
    await savePoll(connection, id, poll);
    await connection.commit();
    res.json({ message: 'Notice updated successfully' });
  } catch (error) {
    await connection.rollback();
    console.error('Update notice error:', error);
    res.status(500).json({ message: error.message || 'Server error' });
  } finally {
    connection.release();
  }
};

const publishNotice = async (req, res) => {
  try {
    await ensurePollSchema();
    await promisePool.query("UPDATE notices SET status = 'published', updated_at = NOW() WHERE id = ?", [req.params.id]);
    res.json({ message: 'Notice published successfully' });
  } catch (error) {
    console.error('Publish notice error:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

const closePoll = async (req, res) => {
  try {
    await ensurePollSchema();
    const { id } = req.params;
    const [polls] = await promisePool.query('SELECT p.*, n.title FROM notice_polls p JOIN notices n ON n.id = p.notice_id WHERE n.id = ?', [id]);
    if (!polls.length) return res.status(404).json({ message: 'Poll not found' });
    await promisePool.query('UPDATE notice_polls SET closed_at = NOW(), updated_at = NOW() WHERE id = ?', [polls[0].id]);
    await notifyResidents(`Poll ended: ${polls[0].title}`, 'Poll results are now available in the notice board.', id);
    res.json({ message: 'Poll closed successfully' });
  } catch (error) {
    console.error('Close poll error:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

const castNoticeVote = async (req, res) => {
  const connection = await promisePool.getConnection();
  try {
    await ensurePollSchema();
    if (req.user.role !== 'resident') return res.status(403).json({ message: 'Only residents can vote in notice polls' });
    const { id } = req.params;
    const selectedOptionIds = asArray(req.body.option_ids || req.body.optionIds).map(Number).filter(Boolean);
    const [notices] = await connection.query('SELECT * FROM notices WHERE id = ?', [id]);
    if (!notices.length) return res.status(404).json({ message: 'Notice not found' });

    const notice = await attachPolls(notices[0], req.user);
    const poll = notice.poll;
    if (!poll) return res.status(400).json({ message: 'This notice does not have a poll' });
    if (pollStatus(poll) !== 'Poll Active') return res.status(400).json({ message: 'Voting is not active for this poll' });
    if (!selectedOptionIds.length) return res.status(400).json({ message: 'Select at least one option' });
    if (poll.poll_type !== 'multiple_choice' && selectedOptionIds.length > 1) return res.status(400).json({ message: 'Only one option can be selected' });

    const validIds = new Set(poll.options.map((option) => Number(option.id)));
    if (selectedOptionIds.some((optionId) => !validIds.has(optionId))) return res.status(400).json({ message: 'Invalid poll option selected' });

    const [existing] = await connection.query('SELECT id FROM notice_poll_votes WHERE poll_id = ? AND resident_id = ?', [poll.id, req.user.id]);
    if (existing.length && !poll.allow_vote_change) return res.status(409).json({ message: 'You have already voted in this poll' });

    const [userRows] = await connection.query(
      `SELECT COALESCE(f.flat_no, '') AS flat_no
       FROM users u
       LEFT JOIN flats f ON f.id = u.flat_id
       WHERE u.id = ?`,
      [req.user.id]
    );
    const flatNo = userRows[0]?.flat_no || null;

    await connection.beginTransaction();
    if (existing.length) {
      await connection.query('DELETE FROM notice_poll_votes WHERE poll_id = ? AND resident_id = ?', [poll.id, req.user.id]);
    }
    for (const optionId of selectedOptionIds) {
      await connection.query(
        'INSERT INTO notice_poll_votes (poll_id, option_id, resident_id, flat_no) VALUES (?, ?, ?, ?)',
        [poll.id, optionId, req.user.id, flatNo]
      );
    }
    await connection.commit();
    res.json({ message: poll.allow_vote_change && existing.length ? 'Vote updated successfully' : 'Vote submitted successfully' });
  } catch (error) {
    await connection.rollback();
    console.error('Cast notice vote error:', error);
    res.status(500).json({ message: error.message || 'Server error' });
  } finally {
    connection.release();
  }
};

const getNoticeStats = async (req, res) => {
  try {
    await ensurePollSchema();
    await sendPollTimelineNotifications();
    const [rows] = await promisePool.query(`
      SELECT
        (SELECT COUNT(*)::int FROM notices) AS total_notices,
        (SELECT COUNT(*)::int FROM notice_polls) AS notices_with_polls,
        (SELECT COUNT(*)::int FROM notice_polls WHERE closed_at IS NULL AND NOW() BETWEEN start_at AND end_at) AS active_polls,
        (SELECT COUNT(*)::int FROM notice_polls WHERE closed_at IS NOT NULL OR NOW() > end_at) AS closed_polls,
        (SELECT COUNT(DISTINCT (poll_id, resident_id))::int FROM notice_poll_votes) AS total_votes
    `);
    const eligible = await eligibleResidentCount();
    const stats = rows[0] || {};
    const pollCount = Number(stats.notices_with_polls || 0);
    const totalVotes = Number(stats.total_votes || 0);
    res.json({
      ...stats,
      total_notices: Number(stats.total_notices || 0),
      notices_with_polls: pollCount,
      active_polls: Number(stats.active_polls || 0),
      closed_polls: Number(stats.closed_polls || 0),
      total_votes: totalVotes,
      participation_percent: eligible && pollCount ? Math.round((totalVotes / (eligible * pollCount)) * 100) : 0
    });
  } catch (error) {
    console.error('Notice stats error:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

const deleteNotice = async (req, res) => {
  try {
    await ensurePollSchema();
    await promisePool.query('DELETE FROM notices WHERE id = ?', [req.params.id]);
    res.json({ message: 'Notice deleted successfully' });
  } catch (error) {
    console.error('Delete notice error:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

module.exports = {
  getAllNotices,
  getLatestNotices,
  getNoticeById,
  createNotice,
  updateNotice,
  publishNotice,
  closePoll,
  castNoticeVote,
  getNoticeStats,
  deleteNotice
};
