const promisePool = require('../config/database');
const ADMINS = new Set(['admin', 'super_admin']);
const n = value => Number(value || 0);
const account = method => String(method || '').trim().toLowerCase() === 'cash' ? 'CASH' : 'BANK';
const parseFy = value => { const m=String(value||'').match(/^(\d{4})-(\d{4})$/); if(!m||+m[2]!==+m[1]+1||+m[1]<2000||+m[1]>2200)return null; return +m[1]; };
const monthPeriod = (fy,m) => { m=+m; if(m<1||m>12)return null; const y=m>=4?fy:fy+1; return {start:`${y}-${String(m).padStart(2,'0')}-01`,end:m===12?`${y+1}-01-01`:`${y}-${String(m+1).padStart(2,'0')}-01`,month:m,year:y}; };

async function openingRecord(date){ const [r]=await promisePool.query('SELECT effective_date,bank_amount,cash_amount FROM accounting_opening_balances WHERE effective_date<=? ORDER BY effective_date DESC LIMIT 1',[date]); return r[0]||null; }
async function movements(start,end){
  const [inc]=await promisePool.query("SELECT COALESCE(payment_method,'Unknown') method,SUM(paid_amount) amount FROM maintenance WHERE status='Paid' AND payment_date>=? AND payment_date<? AND paid_amount>0 GROUP BY COALESCE(payment_method,'Unknown')",[start,end]);
  const [exp]=await promisePool.query("SELECT account_type,SUM(amount) amount FROM maintenance_expenses WHERE status='Paid' AND expense_date>=? AND expense_date<? GROUP BY account_type",[start,end]);
  const x={bankIncome:0,cashIncome:0,bankExpenses:0,cashExpenses:0}; inc.forEach(r=>x[account(r.method)==='CASH'?'cashIncome':'bankIncome']+=n(r.amount)); exp.forEach(r=>x[r.account_type==='CASH'?'cashExpenses':'bankExpenses']+=n(r.amount)); return x;
}
async function balancesAt(date){ const o=await openingRecord(date); if(!o)return null; const x=await movements(String(o.effective_date).slice(0,10),date); return {bank:n(o.bank_amount)+x.bankIncome-x.bankExpenses,cash:n(o.cash_amount)+x.cashIncome-x.cashExpenses}; }
async function summary(start,end){ const o=await balancesAt(start); if(!o)return null; const x=await movements(start,end); const bc=o.bank+x.bankIncome-x.bankExpenses,cc=o.cash+x.cashIncome-x.cashExpenses; return {periodStart:start,periodEndExclusive:end,bankOpening:o.bank,cashOpening:o.cash,totalOpening:o.bank+o.cash,...x,totalIncome:x.bankIncome+x.cashIncome,totalExpenses:x.bankExpenses+x.cashExpenses,bankClosing:bc,cashClosing:cc,totalClosing:bc+cc,netAmount:x.bankIncome+x.cashIncome-x.bankExpenses-x.cashExpenses}; }
async function collection(start,end){ const [r]=await promisePool.query("SELECT COUNT(*) bills_generated,SUM(CASE WHEN status='Paid' THEN 1 ELSE 0 END) paid,SUM(CASE WHEN status IN ('Pending','Partial') THEN 1 ELSE 0 END) pending,SUM(CASE WHEN status IN ('Under Review','Verification Pending','Clarification Requested') THEN 1 ELSE 0 END) verification_pending,SUM(CASE WHEN status='Rejected' THEN 1 ELSE 0 END) rejected,SUM(CASE WHEN status='Overdue' OR (due_date<CURRENT_DATE AND remaining_amount>0) THEN 1 ELSE 0 END) overdue,SUM(CASE WHEN COALESCE(write_off_amount,0)>0 THEN 1 ELSE 0 END) written_off,COALESCE(SUM(CASE WHEN status='Paid' THEN paid_amount ELSE 0 END),0) paid_amount,COALESCE(SUM(remaining_amount),0) pending_amount,COALESCE(SUM(total_amount),0) billed_amount,COALESCE(SUM(write_off_amount),0) write_off_amount FROM maintenance WHERE due_date>=? AND due_date<?",[start,end]); const x=r[0]||{},b=n(x.billed_amount),p=n(x.paid_amount); return {billsGenerated:n(x.bills_generated),paid:n(x.paid),pending:n(x.pending),verificationPending:n(x.verification_pending),rejected:n(x.rejected),overdue:n(x.overdue),writtenOff:n(x.written_off),paidAmount:p,pendingAmount:n(x.pending_amount),billedAmount:b,writeOffAmount:n(x.write_off_amount),collectionRate:b>0?Math.round(p*10000/b)/100:null}; }
async function breakdown(start,end){ const [i]=await promisePool.query("SELECT COALESCE(payment_method,'Unknown') method,SUM(paid_amount) amount FROM maintenance WHERE status='Paid' AND payment_date>=? AND payment_date<? AND paid_amount>0 GROUP BY COALESCE(payment_method,'Unknown')",[start,end]); const [e]=await promisePool.query("SELECT category,account_type,SUM(amount) amount FROM maintenance_expenses WHERE status='Paid' AND expense_date>=? AND expense_date<? GROUP BY category,account_type ORDER BY category",[start,end]); return {income:i.map(r=>({category:'Maintenance',accountType:account(r.method),amount:n(r.amount)})),expenses:e.map(r=>({category:r.category,accountType:r.account_type,amount:n(r.amount)}))}; }
async function ledger(start,end,requested){
  const [income]=await promisePool.query(`SELECT m.payment_date transaction_date,'INCOME' transaction_type,COALESCE(m.title,'Maintenance collection') description,m.paid_amount amount,m.payment_method,p.transaction_id reference_number,m.status approval_status,approver.name approved_by
    FROM maintenance m LEFT JOIN payments p ON p.bill_id=m.id AND p.payment_status='Paid' LEFT JOIN users approver ON approver.id=p.approved_by
    WHERE m.status='Paid' AND m.payment_date>=? AND m.payment_date<? AND m.paid_amount>0 ORDER BY m.payment_date,m.id`,[start,end]);
  const [expenses]=await promisePool.query(`SELECT e.expense_date transaction_date,'EXPENSE' transaction_type,COALESCE(e.description,e.category) description,e.amount,e.payment_method,e.expense_number reference_number,e.status approval_status,creator.name approved_by
    FROM maintenance_expenses e LEFT JOIN users creator ON creator.id=e.created_by WHERE e.status='Paid' AND e.account_type=? AND e.expense_date>=? AND e.expense_date<? ORDER BY e.expense_date,e.id`,[requested,start,end]);
  const rows=[...income.filter(r=>account(r.payment_method)===requested),...expenses].sort((a,b)=>String(a.transaction_date).localeCompare(String(b.transaction_date)));
  const opening=await balancesAt(start); let running=opening?.[requested==='CASH'?'cash':'bank']||0;
  return rows.map(r=>{running+=r.transaction_type==='INCOME'?n(r.amount):-n(r.amount);return {...r,amount:n(r.amount),runningBalance:running};});
}
async function flatPayments(start,end,resident){
  const [rows]=await promisePool.query(`SELECT f.flat_no,u.name resident_name,m.month,m.year,m.total_amount bill_amount,m.paid_amount,m.remaining_amount,m.status,p.paid_at payment_date,p.payment_method,p.receipt_number,p.payment_status verification_status
    FROM maintenance m JOIN flats f ON f.id=m.flat_id JOIN users u ON u.id=m.resident_id
    LEFT JOIN LATERAL (SELECT paid_at,payment_method,receipt_number,payment_status FROM payments WHERE bill_id=m.id ORDER BY created_at DESC LIMIT 1) p ON TRUE
    WHERE m.due_date>=? AND m.due_date<? ORDER BY f.wing,f.flat_no,m.year,m.month`,[start,end]);
  return rows.map(r=>resident?{flatNo:r.flat_no,month:r.month,year:r.year,billAmount:n(r.bill_amount),paidAmount:n(r.paid_amount),pendingAmount:n(r.remaining_amount),status:r.status,paymentDate:r.payment_date,receiptNumber:r.receipt_number}:{flatNo:r.flat_no,residentName:r.resident_name,month:r.month,year:r.year,billAmount:n(r.bill_amount),paidAmount:n(r.paid_amount),pendingAmount:n(r.remaining_amount),status:r.status,paymentDate:r.payment_date,paymentMethod:r.payment_method,receiptNumber:r.receipt_number,verificationStatus:r.verification_status});
}
async function annual(req,res,resident=false){ try{ if(!(ADMINS.has(req.user?.role)||(resident&&req.user?.role==='resident')))return res.status(403).json({message:'Access denied'}); const fy=parseFy(req.query.financialYear); if(!fy)return res.status(400).json({message:'financialYear must be YYYY-YYYY'}); const start=`${fy}-04-01`,end=`${fy+1}-04-01`,s=await summary(start,end); if(!s)return res.json({available:false,reason:'Opening balance has not been configured.'}); const months=[]; for(let k=0;k<12;k++){const m=((3+k)%12)+1,p=monthPeriod(fy,m);months.push({month:m,year:p.year,...await summary(p.start,p.end)});} res.json({available:true,financialYear:`${fy}-${fy+1}`,summary:s,months,collection:await collection(start,end),...await breakdown(start,end)}); }catch(e){console.error('Annual report error',e);res.status(500).json({message:'Unable to generate report'});} }
async function monthly(req,res){ try{if(!ADMINS.has(req.user?.role))return res.status(403).json({message:'Access denied'});const y=+req.query.year,m=+req.query.month;if(!Number.isInteger(y)||y<2000||y>2200||m<1||m>12)return res.status(400).json({message:'Valid year and month are required'});const p=monthPeriod(m>=4?y:y-1,m),s=await summary(p.start,p.end);if(!s)return res.json({available:false,reason:'Opening balance has not been configured.'});res.json({available:true,month:m,year:y,summary:s,collection:await collection(p.start,p.end),...await breakdown(p.start,p.end),bankTransactions:await ledger(p.start,p.end,'BANK'),cashTransactions:await ledger(p.start,p.end,'CASH'),flatPayments:await flatPayments(p.start,p.end,false)});}catch(e){console.error('Monthly report error',e);res.status(500).json({message:'Unable to generate report'});} }
async function residentPayments(req,res){try{if(req.user?.role!=='resident')return res.status(403).json({message:'Access denied'});const y=+req.query.year,m=+req.query.month;if(!Number.isInteger(y)||m<1||m>12)return res.status(400).json({message:'Valid year and month are required'});const p=monthPeriod(m>=4?y:y-1,m);res.json(await flatPayments(p.start,p.end,true));}catch(e){console.error('Resident payment report error',e);res.status(500).json({message:'Unable to load payment status'});}}
async function setupOpening(req,res){try{if(!ADMINS.has(req.user?.role))return res.status(403).json({message:'Access denied'});const {effectiveDate,bankAmount,cashAmount,reason}=req.body;if(!/^\d{4}-\d{2}-\d{2}$/.test(effectiveDate||'')||n(bankAmount)<0||n(cashAmount)<0)return res.status(400).json({message:'Valid effectiveDate and non-negative balances are required'});const [old]=await promisePool.query('SELECT id FROM accounting_opening_balances LIMIT 1');if(old.length)return res.status(409).json({message:'Opening balance is already configured; use an audited adjustment workflow.'});const [r]=await promisePool.query('INSERT INTO accounting_opening_balances(effective_date,bank_amount,cash_amount,reason,created_by) VALUES(?,?,?,?,?)',[effectiveDate,bankAmount,cashAmount,reason||'Initial accounting balance',req.user.id]);res.status(201).json({id:r.insertId,message:'Opening balance configured'});}catch(e){console.error('Opening setup error',e);res.status(500).json({message:'Unable to configure opening balance'});}}
module.exports={adminAnnual:(q,s)=>annual(q,s),adminMonthly:monthly,residentTransparency:(q,s)=>annual(q,s,true),residentPayments,setupOpening,balanceForAccount:async(a,d)=>{const b=await balancesAt(d);return b?b[a==='CASH'?'cash':'bank']:null;}};
