-- Drop constraint if exists and add updated status constraints
ALTER TABLE maintenance DROP CONSTRAINT IF EXISTS maintenance_status_check;
ALTER TABLE maintenance ADD CONSTRAINT maintenance_status_check CHECK (status IN ('Paid', 'Pending', 'Overdue', 'Under Review', 'Rejected', 'Partial'));

-- Add columns
ALTER TABLE maintenance ADD COLUMN IF NOT EXISTS penalty_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00;
ALTER TABLE maintenance ADD COLUMN IF NOT EXISTS total_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00;

-- Sync total_amount for existing records
UPDATE maintenance SET total_amount = amount + penalty_amount;

-- Create settings table
CREATE TABLE IF NOT EXISTS maintenance_settings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  fixed_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00 CHECK (fixed_amount >= 0),
  due_day INTEGER NOT NULL CHECK (due_day BETWEEN 1 AND 31),
  late_fee_type VARCHAR(20) NOT NULL CHECK (late_fee_type IN ('fixed', 'percentage')),
  late_fee_value NUMERIC(10, 2) NOT NULL CHECK (late_fee_value >= 0),
  grace_days INTEGER NOT NULL DEFAULT 0 CHECK (grace_days >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE maintenance_settings ENABLE ROW LEVEL SECURITY;
