-- Rename owner_id to current_resident_id in flats table
ALTER TABLE flats RENAME COLUMN owner_id TO current_resident_id;

-- Recreate index for current_resident_id
DROP INDEX IF EXISTS idx_flats_owner_id;
CREATE INDEX IF NOT EXISTS idx_flats_current_resident_id ON flats(current_resident_id);

-- Create flat_transfer_history table
CREATE TABLE IF NOT EXISTS flat_transfer_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  flat_id INTEGER NOT NULL REFERENCES flats(id) ON DELETE CASCADE,
  old_resident_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  new_resident_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  transfer_date DATE NOT NULL DEFAULT CURRENT_DATE,
  transfer_reason TEXT,
  transferred_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index on flat_id for performance
CREATE INDEX IF NOT EXISTS idx_flat_transfer_history_flat_id ON flat_transfer_history(flat_id);

-- Enable Row Level Security (RLS)
ALTER TABLE flat_transfer_history ENABLE ROW LEVEL SECURITY;
