CREATE TABLE IF NOT EXISTS resident_maintenance_categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resident_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  flat_id INTEGER REFERENCES flats(id) ON DELETE CASCADE,
  category_id INTEGER REFERENCES maintenance_categories(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (flat_id, resident_id, category_id)
);

CREATE INDEX IF NOT EXISTS idx_res_maint_cat_flat_id ON resident_maintenance_categories(flat_id);
CREATE INDEX IF NOT EXISTS idx_res_maint_cat_resident_id ON resident_maintenance_categories(resident_id);

ALTER TABLE resident_maintenance_categories ENABLE ROW LEVEL SECURITY;
