CREATE TABLE IF NOT EXISTS flat_category_assignments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  flat_id INTEGER REFERENCES flats(id) ON DELETE CASCADE,
  category_id INTEGER REFERENCES maintenance_categories(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (flat_id, category_id)
);

CREATE INDEX IF NOT EXISTS idx_flat_cat_assign_flat_id ON flat_category_assignments(flat_id);

ALTER TABLE flat_category_assignments ENABLE ROW LEVEL SECURITY;
