ALTER TABLE maintenance
  ADD COLUMN IF NOT EXISTS bill_number VARCHAR(80),
  ADD COLUMN IF NOT EXISTS waiver_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS cancelled_by INTEGER REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE maintenance
  DROP CONSTRAINT IF EXISTS maintenance_status_check;

ALTER TABLE maintenance
  ADD CONSTRAINT maintenance_status_check
  CHECK (status IN ('Draft', 'Generated', 'Pending', 'Partial', 'Partially Paid', 'Paid', 'Overdue', 'Under Review', 'Pending Verification', 'Rejected', 'Waived', 'Cancelled'));

UPDATE maintenance
SET bill_number = CONCAT('BILL-', id)
WHERE bill_number IS NULL OR bill_number = '';

CREATE UNIQUE INDEX IF NOT EXISTS idx_maintenance_bill_number ON maintenance(bill_number);
CREATE INDEX IF NOT EXISTS idx_maintenance_flat_period ON maintenance(flat_id, month, year)
WHERE flat_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_maintenance_period_status ON maintenance(year, month, status);

ALTER TABLE payments
  ADD COLUMN IF NOT EXISTS admin_notes TEXT,
  ADD COLUMN IF NOT EXISTS is_duplicate BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS duplicate_reason TEXT,
  ADD COLUMN IF NOT EXISTS corrected_amount NUMERIC(12, 2),
  ADD COLUMN IF NOT EXISTS clarification_message TEXT,
  ADD COLUMN IF NOT EXISTS clarification_requested_at TIMESTAMPTZ;

ALTER TABLE payments
  DROP CONSTRAINT IF EXISTS payments_payment_status_check;

ALTER TABLE payments
  ADD CONSTRAINT payments_payment_status_check
  CHECK (payment_status IN ('Pending', 'Under Review', 'Pending Verification', 'Needs Clarification', 'Duplicate', 'Amount Mismatch', 'Approved', 'Paid', 'Rejected'));

CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_receipt_number ON payments(receipt_number)
WHERE receipt_number IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_payments_transaction_id ON payments(transaction_id)
WHERE transaction_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS maintenance_waivers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_id INTEGER NOT NULL REFERENCES maintenance(id) ON DELETE CASCADE,
  resident_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  flat_id INTEGER REFERENCES flats(id) ON DELETE SET NULL,
  waiver_type VARCHAR(40) NOT NULL DEFAULT 'Partial waiver',
  original_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
  waiver_amount NUMERIC(12, 2) NOT NULL CHECK (waiver_amount > 0),
  final_payable_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
  reason TEXT NOT NULL,
  approval_reference VARCHAR(120),
  approval_date DATE,
  attachment_url TEXT,
  admin_note TEXT,
  approved_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS resident_advance_balances (
  resident_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  opening_balance NUMERIC(12, 2) NOT NULL DEFAULT 0,
  available_balance NUMERIC(12, 2) NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS advance_transactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resident_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  flat_id INTEGER REFERENCES flats(id) ON DELETE SET NULL,
  bill_id INTEGER REFERENCES maintenance(id) ON DELETE SET NULL,
  transaction_type VARCHAR(30) NOT NULL CHECK (transaction_type IN ('Credit', 'Applied', 'Refund')),
  amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
  payment_method VARCHAR(50),
  transaction_id VARCHAR(255),
  notes TEXT,
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS maintenance_reminders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_id INTEGER REFERENCES maintenance(id) ON DELETE CASCADE,
  resident_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  flat_id INTEGER REFERENCES flats(id) ON DELETE SET NULL,
  message TEXT NOT NULL,
  sent_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_maintenance_waivers_bill_id ON maintenance_waivers(bill_id);
CREATE INDEX IF NOT EXISTS idx_advance_transactions_resident_id ON advance_transactions(resident_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_reminders_bill_id ON maintenance_reminders(bill_id);

ALTER TABLE maintenance_waivers ENABLE ROW LEVEL SECURITY;
ALTER TABLE resident_advance_balances ENABLE ROW LEVEL SECURITY;
ALTER TABLE advance_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance_reminders ENABLE ROW LEVEL SECURITY;
